on:
  push:
  schedule:
    - cron: '0 3 * * *'

name: transplantation

jobs:
  transplantation:
    name: "Incorporating the latest changes"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Transplant book contents
        uses: LTLA/TrojanBookBuilder@master
        with:
          book: Bioconductor/OrchestratingSingleCellAnalysis
      - name: Committing to master
        run: | 
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Incorporate latest changes from book." || true
          git push
